# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-80c28656-8623-4165-b62f-1ffa3d3a184c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-80c28656-8623-4165-b62f-1ffa3d3a184c".device = "/dev/disk/by-uuid/80c28656-8623-4165-b62f-1ffa3d3a184c";
  boot.initrd.luks.devices."luks-23c4f694-c4ab-48a8-80a1-fb3651d2040d".device = "/dev/disk/by-uuid/23c4f694-c4ab-48a8-80a1-fb3651d2040d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0C61-34F9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-23c4f694-c4ab-48a8-80a1-fb3651d2040d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
