# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/580b7a77-3647-4bee-9d00-923740533618";
      fsType = "ext4";
    };

  fileSystems."/mnt/media/SSD" =
    { device = "/dev/disk/by-label/SSD";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ];
    };

  boot.initrd.luks.devices."luks-bf32fac4-f0c7-4f32-af7f-4f60fe3cf454".device = "/dev/disk/by-uuid/bf32fac4-f0c7-4f32-af7f-4f60fe3cf454";
  boot.initrd.luks.devices."luks-44f4f46b-297a-4f25-b58d-c75fc679d2a7".device = "/dev/disk/by-uuid/44f4f46b-297a-4f25-b58d-c75fc679d2a7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9B82-CC39";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7337343e-7c58-4af9-99b7-43019f2682a8"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware = {
    graphics = {
        enable = true;
        enable32Bit = true;
    };
  };

  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot

}
